parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: aeurus
    database_user: aeurus
    database_password: aeurus
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 42b09e3feb68e1010dcef971ca555913b10
    database_path: null
